export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAILED = "PRODUCT_LIST_FAILED";

export const PRICE_LIST_REQUEST = "PRICE_LIST_REQUEST";
export const PRICE_LIST_SUCCESS = "PRICE_LIST_SUCCESS";
export const PRICE_LIST_FAILED = "PRICE_LIST_FAILED";
